import styles from "../page.module.css";

export default function Steps() {
  return (
    <div className={styles.steps}>
      <div className={styles.step}><div className={`${styles['step-num']}`}>01 / PLACE <span>↗</span></div><h3>Place paper on desk</h3><p>Drop any PDF — the wood desk accepts it like real paper. Up to 300 pages, even scanned.</p><div className={`${styles['step-visual']}`}><div className={styles.upload}><div className={styles.ico}>↑</div><strong>Drop PDF on desk</strong><br /><span style={{fontSize:'11px', color:'#7A6A54'}}>or click to browse • 50MB</span></div><div className={`${styles['mini-row']}`}>UPSC_2022.pdf <span style={{background:'linear-gradient(180deg,#FFD88A,#C9A86A)', padding:'2px 7px', borderRadius:'999px', fontSize:'11px', border:'1px solid #8C6A2E'}}>12.4 MB</span></div></div></div>
      <div className={styles.step}><div className={`${styles['step-num']}`}>02 / LEDGER <span>✦</span></div><h3>Brass ledger reads</h3><p>Our AI ledger stamps duration, negatives, sections — like a hall invigilator checking your paper.</p><div className={`${styles['step-visual']}`}><div className={styles.grid2}><div className={`${styles['mini-card']}`}><small>DURATION</small><br /><strong>180 mins</strong></div><div className={`${styles['mini-card']}`}><small>MARKING</small><br /><strong>+4 −1</strong></div><div className={`${styles['mini-card']}`}><small>SECTIONS</small><br /><strong>3 found</strong></div><div className={`${styles['mini-card']}`}><small>QUESTIONS</small><br /><strong>90 parsed</strong></div></div></div></div>
      <div className={styles.step}><div className={`${styles['step-num']}`}>03 / ATTEMPT <span>▶</span></div><h3>Monitor becomes exam</h3><p>The desk monitor glows — palette, timer, mark-for-review, exactly like NTA’s hall.</p><div className={`${styles['step-visual']}`} style={{padding:'0', overflow:'hidden'}}><div style={{display:'flex', justifyContent:'space-between', padding:'10px 12px', fontSize:'11px', fontWeight:'800', borderBottom:'1px solid #E8D9B0'}}><span>Q 14 / 90</span><span style={{background:'#1A1208', color:'#FFD88A', padding:'4px 8px', borderRadius:'999px'}}>01:42:11</span></div><div style={{padding:'12px'}}><div className={`${styles.rule} ${styles.w90}`}></div><div className={`${styles.rule} w70`}></div><div style={{display:'grid', gridTemplateColumns:'repeat(5,1fr)', gap:'6px', marginTop:'10px'}}><span className={`${styles.pal} ${styles.ans}`}>1</span><span className={`${styles.pal} ${styles.mark}`}>2</span><span className={styles.pal}>3</span><span className={styles.pal}>4</span><span className={styles.pal}>5</span></div></div></div></div>
    </div>
  );
}
